### ISSUE TITLE
Invoking Perforce (graphical) diff on a new thread is broken

### ISSUE THREAD

**Issue by maheshjag** [ericmartel/Sublime-Text-2-Perforce-Plugin#12]
On Windows XP SP3, with ST2 Build 2195, Perforce integration 1.0.13, this is the error that I see. Please note that there was no issue with graphical diff earlier. 

Perforce: Launching thread for Graphical Diff
Exception in thread Thread-28:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\Perforce.py", line 483, in run
  File ".\Perforce.py", line 231, in PerforceCommandOnFile
  File ".\Perforce.py", line 55, in ConstructCommand
  File ".\Perforce.py", line 60, in getPerforceConfigFromPreferences
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

I wish I knew Python so I could help code-wise, but I am more into JS and Perl

**Comment by ericmartel** [comment]
I just reverted a merge request I received, it was causing this problem. I'll try to reimplement properly the feature

Thanks!

**Comment by maheshjag** [comment]
Thanks Eric, greatly appreciate your time on this

**Comment by maheshjag** [comment]
Update: I restarted ST2, and reconnected to Perforce (using the P4 GUI client), and now the diff on a new thread seems to work. So, the issue I reported yesterday could be a false alarm / red herring.
