### ISSUE TITLE
Sublime text hangs when using perforce plugin

### ISSUE THREAD

**Issue by nirarad** [ericmartel/Sublime-Text-2-Perforce-Plugin#18]
Trying to login or automatic check-out will hang sublime text 2.
I'm using a Mac Pro 4,1 with OSX 10.7.5

Reinstalling Perforce plugin does not solve the issue.

**Comment by nirarad** [comment]
My mistake, I had the wrong IP written in .bash_profile
So the real bug here is that perforce plugin does not warn when connection failed.
Instead it just hangs.

**Comment by ericmartel** [comment]
The plugin only waits for p4 to complete. Unfortunately this process is not asynchronous. This is something I'm tackling in my ST3 version
