### ISSUE TITLE
recent update seems to have broke the p4config settings

### ISSUE THREAD

**Issue by pjkix** [ericmartel/Sublime-Text-2-Perforce-Plugin#21]
After a recent update (at least on mac) I keep getting the "file(s) not on client" error.
looks like the way the plugin picks up p4config settings has changed again ... p4v and p4 CLI still work fine however. 

Sublime Text: v 2.0.1, Build 2217
Perforce Plugin Version: 1.0.14
$ p4 -V
Rev. P4/DARWIN90X86_64/2013.1/610569 (2013/03/19).

anyone else having this problem?

**Comment by pjkix** [comment]
ok i seem to have fixed the config issue somewhat by un-commenting this line in Perforce.py  

```
    # Revert change until threading is fixed
    command = getPerforceConfigFromPreferences(command)
```

but i still don't know why it's not picking up the settings from .bash_profile

**Comment by ericmartel** [comment]
I just submitted the fix, sorry, a fellow Mac user suggested a patch (which I couldn't test since I don't have a Mac) that seemed to break the plugin!
