### ISSUE TITLE
Improved setup instructions

### ISSUE THREAD

**Issue by davidfstr** [ericmartel/Sublime-Text-2-Perforce-Plugin#24]
The plugin imports `~/bash_profile` on OS X to get environment variables like $PATH (that point to the p4 tool) and environment variables like $P4USER, $P4PASSWD, and $P4CLIENT. If the preceding are not setup incorrectly then most commands will fail with "not in client root" warnings.

It would be good to have some setup instructions [here](http://www.ericmartel.com/sublime-text-2-perforce-plugin/) that cover this and other environmental issues when installing the plugin for the first time.

**Comment by ericmartel** [comment]
Hi David,

Thanks for the input!  The plugin was initially developed on Windows where the connection settings can be handled automatically with P4Win.

I'm in the process of rewriting the plugin, adding a way to connect from within the plugin, it should be much better but unfortunately it takes quite some time to develop!

Thanks!

Eric

**Comment by crdesai** [comment]
@ericmartel  I have perforce client installed on my Windows machine, and I downloaded this plugin for Sublime Text 2, but read only files are not automatically checked out when I start modifying the files or try saving them. Do I need to change any settings to make it work?

**Comment by ericmartel** [comment]
@crdesai take a look at your "p4 info" from the command line, if it doesn't look valid, set up manually P4USER, P4PASSWD, and P4CLIENT

**Comment by crdesai** [comment]
@ericmartel I added .p4settings file at my P4 workspace root, but I still could not get the plugin to work. Where does the plugin get P4CLIENT, P4USER values from? Do I need to set these as environment variables on my Windows machine?

**Comment by ericmartel** [comment]
@crdesai the easiest way is to use "p4 set" (which will be fully managed in the next version of the plugin).  See http://www.perforce.com/perforce/r12.2/manuals/cmdref/_env.html
