### ISSUE TITLE
GetPendingChangelists should limit to current user

### ISSUE THREAD

**Issue by tajayi** [ericmartel/Sublime-Text-2-Perforce-Plugin#3]
I recently discovered sublime text and I'm loving it so far
I just downloaded the perforce plugin and it seems excellently executed.. The one thing i had to modify in Perforce.py immediately was the GetPendingChangelists function
I work in a multi-user environment and i didn't want it listing changes which i didn't own.
modified it to

 command = 'p4 changes -s pending -u myUserName'

Thanks for the great plugin.

**Comment by ericmartel** [comment]
Please test the latest version, let me know if you have any problems

**Comment by tajayi** [comment]
Works. Thanks
