### ISSUE TITLE
checkout files in root folder

### ISSUE THREAD

**Issue by crazydc** [ericmartel/Sublime-Text-2-Perforce-Plugin#33]
If files are in the root directory of the client it doesnt think these files are in the client workspace.

I have a very flat development line and here is my example:

Client main:
-file1
-folder1
     |---- file2
     |---- file3

File 2 and 3 are fine to checkout and all sub directories are but the file1 doesn't checkout as it thinks it not in that client.

**Comment by ericmartel** [comment]
Hi,

My depots always start off with a folder for each project, so I have never tested this case.

I'll test it tonight and see that the bug is corrected asap

Thanks

**Comment by crazydc** [comment]
Yea I understand, I only have a few files there. It's because I make my workspace view very restricted to what files and folder I need. If you need me to test anything please do let me know.

**Comment by crazydc** [comment]
Looking into the code at line 166 if I change it to = 1 I can auto checkout files. 

I am not a very good python coder but that seem to solve the issue for now for me.

**Comment by ericmartel** [comment]
Ok!  as long as you work solely on files that are within your workspace, you should be fine, but that change will have some side effects :)

**Comment by ericmartel** [comment]
I validated on my side and I have no problem running operations on files at root level.

If you still have issues that annoy you, can you please reopen an issue with more information about your system?

Thanks
