### ISSUE TITLE
plugin reports error while saving new files in directories where p4 isn't configured

### ISSUE THREAD

**Issue by coldnebo** [ericmartel/Sublime-Text-2-Perforce-Plugin#37]
I have a mix of separate perforce and git directories (and some not under source control).

The perforce plugin however displays an error modal whenever saving a new file outside of a p4 clientspec directory:
- "Perforce Plugin: p4 info didn't supply a valid clientspec, launching p4 client."

This happens because the script running `p4 info` finds this:
`Client unknown`
instead of this:
`Client root: <dir>`

Ordinarily this would be an error condition, however in the case of automatic mark for add, it should be handled silently, as this may also be a git or uncontrolled directory.

I checked to see if there were options to select which dirs the plugin could be either enabled/disabled for (an alternative solution), but couldn't find any?

In general, you may wish to disable the plugin functionality if p4 clientspec isn't setup properly in a directory.

**Comment by ericmartel** [comment]
Hi,

Thanks for the feedback, I totally agree with you that this should not happen, the plugin should ignore auto add in folders that aren't tracked.

I'll try to take a look at it later tonight!

Thanks

**Comment by ericmartel** [comment]
Pushed an update, please reopen the issue if it's not fixed after an update

**Comment by coldnebo** [comment]
Actually, error still happens because GetClientRoot raises error during detection

See [Perforce.py, line 127](https://github.com/ericmartel/Sublime-Text-2-Perforce-Plugin/blob/master/Perforce.py#L127).

**Comment by ericmartel** [comment]
Ahh I see my bad, I did improve the checks but yeah, I didn't have a case where the client got invalid
