### ISSUE TITLE
Causes 20-30 sec delay saving files when p4 server unavailable

### ISSUE THREAD

**Issue by GrantGatchel** [ericmartel/Sublime-Text-2-Perforce-Plugin#4]
When I use Sublime Text 2 with the Perforce plugin on my laptop at work, the connection seems fine and there is no noticeable lag. However, when I open the same project at home, saving files causes a 20 to 30 second delay for every file, regardless if its actually in a perforce project or not.

**Comment by ericmartel** [comment]
Hi,

Is it possible that your laptop is running MacOSX?

I'll be looking into your issues today.

Thanks

**Comment by GrantGatchel** [comment]
Windows XP. When I connect via VPN, then the lag goes away. This is particularly annoying for files that I'm editing  when either not connected over VPN or when my wireless signal goes down (which happens on occasion).

**Comment by ericmartel** [comment]
On my test machine, p4 info returns instantly whether there's a connection or not, but this doesn't seem to always be the case. The "save" function should be faster now (just checked in) as it tests if the file is writable before trying to access p4 info, so you should be able to save your work without having the ~30 secs lag.
