### ISSUE TITLE
Feature: project-specific p4 configuration

### ISSUE THREAD

**Issue by GrantGatchel** [ericmartel/Sublime-Text-2-Perforce-Plugin#5]
I have many different projects, each one having a different client and many of them operating on different servers. It would be extremely helpful to have the user setup defined the defaults (username, common server, common port, etc) and allow the projects to override them.

**Comment by ericmartel** [comment]
If you have time, could you drop me a line at emartel@gmail.com, I'd like to discuss with you about what kind of solution you'd like to have without being too intrusive.  Thanks!

**Comment by GrantGatchel** [comment]
Done. Let's do this.
