### ISSUE TITLE
Opening file from List of checkout files doesnt work

### ISSUE THREAD

**Issue by sahilb** [ericmartel/Sublime-Text-2-Perforce-Plugin#7]
It tends to mess up the case of the path. e.g. 
Lets say the file is at : /Users/abc/Documents/workspace/test.js 

it tries to look up : /users/abc/documents/workspace/test.js

**Comment by ericmartel** [comment]
Should be fixed now

**Comment by sahilb** [comment]
Still a issue, though it looks like a different cause:

For my list of opened files, i have :
t:/>p4 opened
//Demo/trunk/a.xml#40 - edit default change (text)
//Demo/trunk/editor.js#1 - add default change (text)

but the path that Sublime text Perforce plugin parse is: 
/Users/abc/Documents/workspace/trunk/a.xml

It skips the first dir, just after '//'

**Comment by sahilb** [comment]
The path case issue  is fixed though thanks.
